version: '3.8'

services:
  db:
    image: dockerhub.timeweb.cloud/library/postgres:15
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass_key
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d my_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  python_app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass_key

  prometheus:
    image: dockerhub.timeweb.cloud/prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - node-exporter

  node-exporter:
    image: dockerhub.timeweb.cloud/prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"

