---
# tasks/main.yml для роли nginx_docker

- name: Обновляем кэш пакетов apt
  apt:
    update_cache: yes

- name: Устанавливаем классический веб-сервер Nginx
  apt:
    name: nginx
    state: present

- name: Копируем конфигурацию Reverse Proxy в Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
    mode: '0644'
  notify: Перезапустить Nginx

- name: Убеждаемся, что Nginx запущен и работает
  service:
    name: nginx
    state: started
    enabled: yes

